# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-15 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_show', '0002_show_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='release_date',
            field=models.DateField(default=10),
            preserve_default=False,
        ),
    ]
