# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-19 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0004_auto_20191018_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='enddate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='startdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='users',
            field=models.ManyToManyField(related_name='trips', to='exam_app.User'),
        ),
    ]
