# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-21 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0007_auto_20191021_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='other',
            name='users',
            field=models.ManyToManyField(related_name='others', to='exam_app.User'),
        ),
    ]
