# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-21 16:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0008_other_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='other',
            name='users',
        ),
    ]
