# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-21 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0010_auto_20191021_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='others',
            name='users',
            field=models.ManyToManyField(related_name='otherss', to='exam_app.User'),
        ),
    ]
