# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-18 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0002_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.CharField(max_length=255),
        ),
    ]
