# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-18 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0003_auto_20191018_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='regist',
            name='trips',
            field=models.ManyToManyField(related_name='trips', to='exam_app.Trip'),
        ),
    ]
