# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-18 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0004_regist_trips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regist',
            name='trips',
        ),
    ]
