# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-18 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0005_remove_regist_trips'),
    ]

    operations = [
        migrations.AddField(
            model_name='regist',
            name='trips',
            field=models.ManyToManyField(related_name='users', to='exam_app.Trip'),
        ),
    ]
