# Generated by Django 2.2.5 on 2019-10-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecatalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneaker',
            name='sneaker_image',
            field=models.ImageField(upload_to='static'),
        ),
    ]
