# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-22 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecatalog', '0002_auto_20191019_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneaker',
            name='sneaker_image',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
