# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-22 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecatalog', '0003_auto_20191022_0110'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=65)),
                ('dof', models.DateField()),
                ('phone_number', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=65)),
                ('password_conf', models.CharField(max_length=65)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
